#!/usr/bin/env python3

import json

data = {
    "items": []
}

# see https://www.alfredapp.com/help/workflows/inputs/script-filter/json/
with open("cheatsheets.txt", mode="r", encoding="utf8") as f:
    for line in f:
        kw = line.strip()
        data["items"].append({
            "title": kw,
            "arg": kw,
        })

print(json.dumps(data))
